const mongoose = require('mongoose');
const dotenv = require('dotenv');
const Movie = require('./models/Movie');
const connectDB = require('./config/db');

dotenv.config();

const movies = [
  {
    title: "Inception",
    description: "A thief who steals corporate secrets through dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.",
    genre: ["Sci-Fi", "Action", "Thriller"],
    mood: ["Intense", "Thought-provoking", "Suspenseful"],
    contentType: "Movie",
    ageRating: "13+",
    country: "USA",
    releaseYear: 2010,
    rating: 8.8,
    poster: "https://cdn.displate.com/artwork/270x380/2024-10-20/9105188b-877e-4f61-9421-68bf5a741fe2.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/s3TBrRGB1iav7gFOCNx3H31MoES.jpg",
    trailer: "https://www.youtube.com/embed/YoHD9XEInc0",
    duration: "2h 28m",
    pace: "Fast",
    tags: ["dreams", "heist", "mind-bending", "christopher nolan"],
    director: "Christopher Nolan",
    originalLanguage: "English",
    popularity: 9500,
    isTrending: true,
    isTopRated: true
  },
  {
    title: "Parasite",
    description: "Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.",
    genre: ["Drama", "Thriller", "Comedy"],
    mood: ["Dark", "Suspenseful", "Thought-provoking"],
    contentType: "Movie",
    ageRating: "18+",
    country: "Korea",
    releaseYear: 2019,
    rating: 8.5,
    poster: "https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/TU9NIjwzjoKPwQHoHshkFcQUCG.jpg",
    trailer: "https://www.youtube.com/embed/5xH0HfJHsaY",
    duration: "2h 12m",
    pace: "Medium",
    tags: ["social commentary", "family", "korean cinema", "oscar winner"],
    director: "Bong Joon-ho",
    originalLanguage: "Korean",
    popularity: 8900,
    isTrending: true,
    isTopRated: true
  },
  {
    title: "Squid Game",
    description: "Hundreds of cash-strapped players accept a strange invitation to compete in children's games. Inside, a tempting prize awaits with deadly high stakes.",
    genre: ["Drama", "Thriller", "Mystery"],
    mood: ["Dark", "Intense", "Suspenseful"],
    contentType: "K-drama",
    ageRating: "18+",
    country: "Korea",
    releaseYear: 2021,
    rating: 8.0,
    poster: "https://image.tmdb.org/t/p/w500/dDlEmu3EZ0Pgg93K2SVNLCjCSvE.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/qw3J9cNeLioOLoR68WX7z79aCdK.jpg",
    trailer: "https://www.youtube.com/embed/oqxAJKy0ii4",
    duration: "9 episodes",
    episodes: 9,
    seasons: 1,
    pace: "Fast",
    tags: ["survival", "games", "korean drama", "netflix"],
    director: "Hwang Dong-hyuk",
    originalLanguage: "Korean",
    popularity: 9800,
    isTrending: true,
    isTopRated: true
  },
  {
    title: "Your Name",
    description: "Two strangers find themselves linked in a bizarre way. When a connection forms, will distance be the only thing to keep them apart?",
    genre: ["Romance", "Fantasy", "Drama"],
    mood: ["Emotional", "Feel-good", "Thought-provoking"],
    contentType: "Anime",
    ageRating: "13+",
    country: "Japan",
    releaseYear: 2016,
    rating: 8.4,
    poster: "https://image.tmdb.org/t/p/w500/q719jXXEzOoYaps6babgKnONONX.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/dIWwZW7dJJtqC6CgWzYkNVKIUm8.jpg",
    trailer: "https://www.youtube.com/embed/xU47nhruN-Q",
    duration: "1h 46m",
    pace: "Medium",
    tags: ["body swap", "romance", "anime film", "beautiful animation"],
    director: "Makoto Shinkai",
    originalLanguage: "Japanese",
    popularity: 8500,
    isTrending: false,
    isTopRated: true
  },
  {
    title: "Money Heist",
    description: "An unusual group of robbers attempt to carry out the most perfect robbery in Spanish history - stealing 2.4 billion euros from the Royal Mint of Spain.",
    genre: ["Action", "Thriller", "Drama"],
    mood: ["Intense", "Fast-paced", "Suspenseful"],
    contentType: "Web Series",
    ageRating: "18+",
    country: "Spain",
    releaseYear: 2017,
    rating: 8.2,
    poster: "https://image.tmdb.org/t/p/w500/reEMJA1uzscCbkpeRJeTT2bjqUp.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/xGexTKCJDkl12dTW4YCBDXWb1AD.jpg",
    trailer: "https://www.youtube.com/embed/htgjoU3Hzc4",
    duration: "5 seasons",
    episodes: 41,
    seasons: 5,
    pace: "Fast",
    tags: ["heist", "spanish", "netflix", "mastermind"],
    director: "Álex Pina",
    originalLanguage: "Spanish",
    popularity: 9200,
    isTrending: true,
    isTopRated: true
  },
  {
    title: "The Dark Knight",
    description: "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
    genre: ["Action", "Drama", "Thriller"],
    mood: ["Dark", "Intense", "Suspenseful"],
    contentType: "Movie",
    ageRating: "13+",
    country: "USA",
    releaseYear: 2008,
    rating: 9.0,
    poster: "https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/nMKdUUepR0i5zn0y1T4CsSB5chy.jpg",
    trailer: "https://www.youtube.com/embed/EXeTwQWrcwY",
    duration: "2h 32m",
    pace: "Fast",
    tags: ["batman", "joker", "superhero", "christopher nolan"],
    director: "Christopher Nolan",
    originalLanguage: "English",
    popularity: 9700,
    isTrending: false,
    isTopRated: true
  },
  {
    title: "Attack on Titan",
    description: "After his hometown is destroyed and his mother is killed, young Eren Jaeger vows to cleanse the earth of the giant humanoid Titans that have brought humanity to the brink of extinction.",
    genre: ["Action", "Drama", "Fantasy"],
    mood: ["Dark", "Intense", "Emotional"],
    contentType: "Anime",
    ageRating: "18+",
    country: "Japan",
    releaseYear: 2013,
    rating: 9.0,
    poster: "https://image.tmdb.org/t/p/w500/hTP1DtLGFamjfu8WqjnuQdP1n4i.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/rqbCbjB19amtOtFQbb3K2lgm2zv.jpg",
    trailer: "https://www.youtube.com/embed/MGRm4IzK1SQ",
    duration: "4 seasons",
    episodes: 87,
    seasons: 4,
    pace: "Fast",
    tags: ["titans", "survival", "military", "anime series"],
    director: "Tetsurō Araki",
    originalLanguage: "Japanese",
    popularity: 9400,
    isTrending: true,
    isTopRated: true
  },
  {
    title: "Interstellar",
    description: "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
    genre: ["Sci-Fi", "Adventure", "Drama"],
    mood: ["Emotional", "Thought-provoking", "Intense"],
    contentType: "Movie",
    ageRating: "13+",
    country: "USA",
    releaseYear: 2014,
    rating: 8.6,
    poster: "https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/xJHokMbljvjADYdit5fK5VQsXEG.jpg",
    trailer: "https://www.youtube.com/embed/zSWdZVtXT7E",
    duration: "2h 49m",
    pace: "Medium",
    tags: ["space", "time", "family", "christopher nolan"],
    director: "Christopher Nolan",
    originalLanguage: "English",
    popularity: 9100,
    isTrending: false,
    isTopRated: true
  },
  {
    title: "Stranger Things",
    description: "When a young boy disappears, his mother, a police chief and his friends must confront terrifying supernatural forces in order to get him back.",
    genre: ["Sci-Fi", "Horror", "Drama"],
    mood: ["Suspenseful", "Dark", "Emotional"],
    contentType: "Web Series",
    ageRating: "15+",
    country: "USA",
    releaseYear: 2016,
    rating: 8.7,
    poster: "https://image.tmdb.org/t/p/w500/49WJfeN0moxb9IPfGn8AIqMGskD.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/56v2KjBlU4XaOv9rVYEQypROD7P.jpg",
    trailer: "https://www.youtube.com/embed/b9EkMc79ZSU",
    duration: "4 seasons",
    episodes: 34,
    seasons: 4,
    pace: "Medium",
    tags: ["80s", "supernatural", "netflix", "kids"],
    director: "The Duffer Brothers",
    originalLanguage: "English",
    popularity: 9300,
    isTrending: true,
    isTopRated: true
  },
  {
    title: "The Godfather",
    description: "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.",
    genre: ["Drama", "Action"],
    mood: ["Dark", "Intense", "Slow-paced"],
    contentType: "Movie",
    ageRating: "18+",
    country: "USA",
    releaseYear: 1972,
    rating: 9.2,
    poster: "https://image.tmdb.org/t/p/w500/3bhkrj58Vtu7enYsRolD1fZdja1.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/tmU7GeKVybMWFButWEGl2M4GeiP.jpg",
    trailer: "https://www.youtube.com/embed/sY1S34973zA",
    duration: "2h 55m",
    pace: "Slow",
    tags: ["mafia", "family", "classic", "crime"],
    director: "Francis Ford Coppola",
    originalLanguage: "English",
    popularity: 8800,
    isTrending: false,
    isTopRated: true
  },
  {
    title: "Breaking Bad",
    description: "A high school chemistry teacher diagnosed with terminal lung cancer turns to manufacturing and selling methamphetamine to secure his family's future.",
    genre: ["Drama", "Thriller"],
    mood: ["Dark", "Intense", "Suspenseful"],
    contentType: "Web Series",
    ageRating: "18+",
    country: "USA",
    releaseYear: 2008,
    rating: 9.5,
    poster: "https://image.tmdb.org/t/p/w500/ggFHVNu6YYI5L9pCfOacjizRGt.jpg",
    backdrop: "https://wallpaperaccess.com/full/781842.jpg",
    trailer: "https://www.youtube.com/embed/HhesaQXLuRY",
    duration: "5 seasons",
    episodes: 62,
    seasons: 5,
    pace: "Medium",
    tags: ["drugs", "chemistry", "transformation", "amc"],
    director: "Vince Gilligan",
    originalLanguage: "English",
    popularity: 9600,
    isTrending: true,
    isTopRated: true
  },
  {
    title: "Spirited Away",
    description: "During her family's move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches, and spirits, and where humans are changed into beasts.",
    genre: ["Animation", "Fantasy", "Adventure"],
    mood: ["Feel-good", "Emotional", "Thought-provoking"],
    contentType: "Anime",
    ageRating: "All Ages",
    country: "Japan",
    releaseYear: 2001,
    rating: 8.6,
    poster: "https://image.tmdb.org/t/p/w500/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/bSXfU4dwZyBA1vMmXvejdRXBvuF.jpg",
    trailer: "https://www.youtube.com/embed/ByXuk9QqQkk",
    duration: "2h 5m",
    pace: "Medium",
    tags: ["studio ghibli", "spirits", "coming of age", "hayao miyazaki"],
    director: "Hayao Miyazaki",
    originalLanguage: "Japanese",
    popularity: 8400,
    isTrending: false,
    isTopRated: true
  },
  {
    title: "3 Idiots",
    description: "Two friends are searching for their long lost companion. They revisit their college days and recall the memories of their friend who inspired them to think differently.",
    genre: ["Comedy", "Drama"],
    mood: ["Feel-good", "Emotional", "Lighthearted"],
    contentType: "Movie",
    ageRating: "13+",
    country: "India",
    releaseYear: 2009,
    rating: 8.4,
    poster: "https://image.tmdb.org/t/p/w500/66A9MqXOyVFCssoloscw79z8Tew.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/fLmAkzpSf1r4qGx7aZ9BN47BPsK.jpg",
    trailer: "https://www.youtube.com/embed/xvszmNXdM4w",
    duration: "2h 50m",
    pace: "Medium",
    tags: ["friendship", "education", "bollywood", "inspirational"],
    director: "Rajkumar Hirani",
    originalLanguage: "Hindi",
    popularity: 8600,
    isTrending: false,
    isTopRated: true
  },
  {
    title: "The Shawshank Redemption",
    description: "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
    genre: ["Drama"],
    mood: ["Emotional", "Thought-provoking", "Feel-good"],
    contentType: "Movie",
    ageRating: "15+",
    country: "USA",
    releaseYear: 1994,
    rating: 9.3,
    poster: "https://image.tmdb.org/t/p/w500/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/kXfqcdQKsToO0OUXHcrrNCHDBzO.jpg",
    trailer: "https://www.youtube.com/embed/6hB3S9bIaco",
    duration: "2h 22m",
    pace: "Slow",
    tags: ["prison", "friendship", "hope", "classic"],
    director: "Frank Darabont",
    originalLanguage: "English",
    popularity: 9000,
    isTrending: false,
    isTopRated: true
  },
  {
    title: "Fight Club",
    description: "An insomniac office worker and a soap maker form an underground fight club.",
    genre: ["Drama", "Thriller"],
    mood: ["Dark", "Intense"],
    contentType: "Movie",
    ageRating: "18+",
    country: "USA",
    releaseYear: 1999,
    rating: 8.8,
    poster: "https://image.tmdb.org/t/p/w500/bptfVGEQuv6vDTIMVCHjJ9Dz8PX.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/52AfXWuXCHn3UjD17rBruA9f5qb.jpg",
    trailer: "https://www.youtube.com/embed/SUXWAEX2jlg",
    duration: "2h 19m",
    pace: "Medium",
    tags: ["psychological", "cult classic"],
    director: "David Fincher",
    originalLanguage: "English",
    popularity: 8700,
    isTrending: false,
    isTopRated: true
  },
  {
    title: "Avengers: Endgame",
    description: "Superheroes unite to reverse Thanos snap.",
    genre: ["Action", "Adventure"],
    mood: ["Emotional", "Intense"],
    contentType: "Movie",
    ageRating: "13+",
    country: "USA",
    releaseYear: 2019,
    rating: 8.4,
    poster: "https://image.tmdb.org/t/p/w500/or06FN3Dka5tukK1e9sl16pB3iy.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/7RyHsO4yDXtBv1zUU3mTpHeQ0d5.jpg",
    trailer: "https://www.youtube.com/embed/TcMBFSGVi1c",
    duration: "3h 1m",
    pace: "Fast",
    tags: ["marvel", "superheroes"],
    director: "Russo Brothers",
    originalLanguage: "English",
    popularity: 9900,
    isTrending: true,
    isTopRated: true
  },
  {
    title: "Joker",
    description: "A mentally troubled comedian embarks on a downward spiral.",
    genre: ["Drama", "Thriller"],
    mood: ["Dark", "Intense"],
    contentType: "Movie",
    ageRating: "18+",
    country: "USA",
    releaseYear: 2019,
    rating: 8.4,
    poster: "https://image.tmdb.org/t/p/w500/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/n6bUvigpRFqSwmPp1m2YADdbRBc.jpg",
    trailer: "https://www.youtube.com/embed/zAGVQLHvwOY",
    duration: "2h 2m",
    pace: "Medium",
    tags: ["joker","dc","psychological"],
    director: "Todd Phillips",
    originalLanguage: "English",
    popularity: 8900,
    isTrending: true,
    isTopRated: true
  },
  {
    title: "The Matrix",
    description: "A hacker discovers reality is simulation.",
    genre: ["Sci-Fi","Action"],
    mood: ["Dark","Intense"],
    contentType: "Movie",
    ageRating: "13+",
    country: "USA",
    releaseYear: 1999,
    rating: 8.7,
    poster: "https://image.tmdb.org/t/p/w500/aOIuZAjPaRIE6CMzbazvcHuHXDc.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/7u3pxc0K1wx32IleAkLv78MKgrw.jpg",
    trailer: "https://www.youtube.com/embed/vKQi3bBA1y8",
    duration: "2h 16m",
    pace: "Fast",
    tags: ["simulation","sci-fi"],
    director: "Wachowski",
    originalLanguage: "English",
    popularity: 9100,
    isTrending: false,
    isTopRated: true
  },
  {
    title: "Titanic",
    description: "A love story aboard the Titanic.",
    genre: ["Romance","Drama"],
    mood: ["Emotional"],
    contentType: "Movie",
    ageRating: "13+",
    country: "USA",
    releaseYear: 1997,
    rating: 7.9,
    poster: "https://image.tmdb.org/t/p/w500/9xjZS2rlVxm8SFx8kPC3aIGCOYQ.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/3WqF3o5VhZGy2eXK4t4Gx1a4wQn.jpg",
    trailer: "https://www.youtube.com/embed/kVrqfYjkTdQ",
    duration: "3h 14m",
    pace: "Slow",
    tags: ["romance","ship"],
    director: "James Cameron",
    originalLanguage: "English",
    popularity: 8800,
    isTrending: false,
    isTopRated: true
  },
  {
    title: "The Social Network",
    description: "Story of Facebook creation.",
    genre: ["Drama"],
    mood: ["Thought-provoking"],
    contentType: "Movie",
    ageRating: "13+",
    country: "USA",
    releaseYear: 2010,
    rating: 7.7,
    poster: "https://image.tmdb.org/t/p/w500/n0ybibhJtQ5icDqTp8eRytcIHJx.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/z4Ro3sYbS6fG8Kc2jQnQZC0FqJv.jpg",
    trailer: "https://www.youtube.com/embed/lB95KLmpLR4",
    duration: "2h",
    pace: "Medium",
    tags: ["facebook","tech"],
    director: "David Fincher",
    originalLanguage: "English",
    popularity: 8200,
    isTrending: false,
    isTopRated: true
  },
  {
    title: "Dune",
    description: "A noble family becomes embroiled in war.",
    genre: ["Sci-Fi","Adventure"],
    mood: ["Intense"],
    contentType: "Movie",
    ageRating: "13+",
    country: "USA",
    releaseYear: 2021,
    rating: 8.0,
    poster: "https://image.tmdb.org/t/p/w500/d5NXSklXo0qyIYkgV94XAgMIckC.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/iopYFB1b6Bh7FWZh3onQhph1sIH.jpg",
    trailer: "https://www.youtube.com/embed/8g18jFHCLXk",
    duration: "2h 35m",
    pace: "Medium",
    tags: ["desert","future"],
    director: "Denis Villeneuve",
    originalLanguage: "English",
    popularity: 9000,
    isTrending: true,
    isTopRated: true
  },
  {
    title: "Gladiator",
    description: "Roman general seeks revenge.",
    genre: ["Action","Drama"],
    mood: ["Intense"],
    contentType: "Movie",
    ageRating: "15+",
    country: "USA",
    releaseYear: 2000,
    rating: 8.5,
    poster: "https://image.tmdb.org/t/p/w500/ty8TGRuvJLPUmAR1H1nRIsgwvim.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/9W1f7z3KDf4J2kE7F9p1lE5hQof.jpg",
    trailer: "https://www.youtube.com/embed/owK1qxDselE",
    duration: "2h 35m",
    pace: "Fast",
    tags: ["rome","revenge"],
    director: "Ridley Scott",
    originalLanguage: "English",
    popularity: 8600,
    isTrending: false,
    isTopRated: true
  },
  {
    title: "The Prestige",
    description: "Two magicians rivalry.",
    genre: ["Drama","Thriller"],
    mood: ["Dark"],
    contentType: "Movie",
    ageRating: "13+",
    country: "USA",
    releaseYear: 2006,
    rating: 8.5,
    poster: "https://wallpapercave.com/wp/wp4138558.jpg",
    backdrop: "https://wallpapercat.com/w/full/3/e/6/62898-2048x1152-desktop-hd-the-prestige-background-photo.jpg",
    trailer: "https://www.youtube.com/embed/RLtaA9fFNXU",
    duration: "2h 10m",
    pace: "Medium",
    tags: ["magic","twist"],
    director: "Christopher Nolan",
    originalLanguage: "English",
    popularity: 8700,
    isTrending: false,
    isTopRated: true
  },
  {
    title: "Whiplash",
    description: "Drummer pushed by strict teacher.",
    genre: ["Drama"],
    mood: ["Intense"],
    contentType: "Movie",
    ageRating: "15+",
    country: "USA",
    releaseYear: 2014,
    rating: 8.5,
    poster: "https://image.tmdb.org/t/p/w500/oPxnRhyAIzJKGUEdSiwTJQBa3NM.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/6bbZ6XyvgfjhQwbplnUh1LSj1ky.jpg",
    trailer: "https://www.youtube.com/embed/7d_jQycdQGo",
    duration: "1h 47m",
    pace: "Fast",
    tags: ["music","drama"],
    director: "Damien Chazelle",
    originalLanguage: "English",
    popularity: 8400,
    isTrending: false,
    isTopRated: true
  },
  {
    title: "John Wick",
    description: "An ex-hitman seeks vengeance.",
    genre: ["Action","Thriller"],
    mood: ["Fast-paced","Intense"],
    contentType: "Movie",
    ageRating: "18+",
    country: "USA",
    releaseYear: 2014,
    rating: 7.9,
    poster: "https://image.tmdb.org/t/p/w500/5vHssUeVe25bMrof1HyaPyWgaP.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/fZPSd91yGE9fCcCe6OoQr6E3Bev.jpg",
    trailer: "https://www.youtube.com/embed/2AUmvWm5ZDQ",
    duration: "1h 41m",
    pace: "Fast",
    tags: ["action","assassin"],
    director: "Chad Stahelski",
    originalLanguage: "English",
    popularity: 8500,
    isTrending: true,
    isTopRated: false
  },
  {
    title: "The Wolf of Wall Street",
    description: "A stockbroker rises and falls.",
    genre: ["Drama","Comedy"],
    mood: ["Fast-paced","Dark"],
    contentType: "Movie",
    ageRating: "18+",
    country: "USA",
    releaseYear: 2013,
    rating: 8.2,
    poster: "https://image.tmdb.org/t/p/w500/sOxr33wnRuKazR9ClHek73T8qnK.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/8Y43POKjjKDGI9MH89NW0NAzzp8.jpg",
    trailer: "https://www.youtube.com/embed/iszwuX1AK6A",
    duration: "3h",
    pace: "Fast",
    tags: ["finance","biography"],
    director: "Martin Scorsese",
    originalLanguage: "English",
    popularity: 8800,
    isTrending: false,
    isTopRated: true
  },
  {
    title: "La La Land",
    description: "Musician and actress fall in love.",
    genre: ["Romance","Drama"],
    mood: ["Feel-good","Emotional"],
    contentType: "Movie",
    ageRating: "13+",
    country: "USA",
    releaseYear: 2016,
    rating: 8.0,
    poster: "https://image.tmdb.org/t/p/w500/uDO8zWDhfWwoFdKS4fzkUJt0Rf0.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/jC8xZf1XG6IhUZGqIuP89xDSHLV.jpg",
    trailer: "https://www.youtube.com/embed/0pdqf4P9MB8",
    duration: "2h 8m",
    pace: "Slow",
    tags: ["music","romance"],
    director: "Damien Chazelle",
    originalLanguage: "English",
    popularity: 7900,
    isTrending: false,
    isTopRated: true
  },
  {
    title: "The Batman",
    description: "Batman uncovers corruption in Gotham.",
    genre: ["Action","Drama"],
    mood: ["Dark","Intense"],
    contentType: "Movie",
    ageRating: "13+",
    country: "USA",
    releaseYear: 2022,
    rating: 7.8,
    poster: "https://image.tmdb.org/t/p/w500/74xTEgt7R36Fpooo50r9T25onhq.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/b0PlSFdDwbyK0cf5RxwDpaOJQvQ.jpg",
    trailer: "https://www.youtube.com/embed/mqqft2x_Aa4",
    duration: "2h 56m",
    pace: "Medium",
    tags: ["dc","detective"],
    director: "Matt Reeves",
    originalLanguage: "English",
    popularity: 9000,
    isTrending: true,
    isTopRated: false
  },
  {
    title: "Shutter Island",
    description: "Detective investigates asylum.",
    genre: ["Thriller","Mystery"],
    mood: ["Dark","Suspenseful"],
    contentType: "Movie",
    ageRating: "18+",
    country: "USA",
    releaseYear: 2010,
    rating: 8.2,
    poster: "https://image.tmdb.org/t/p/w500/4GDy0PHYX3VRXUtwK5ysFbg3kEx.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/kve20tXwUZpu4GUX8l6X7Z4jmL6.jpg",
    trailer: "https://www.youtube.com/embed/5iaYLCiq5RM",
    duration: "2h 18m",
    pace: "Medium",
    tags: ["twist","mystery"],
    director: "Martin Scorsese",
    originalLanguage: "English",
    popularity: 8700,
    isTrending: false,
    isTopRated: true
  },
  {
    title: "The Conjuring",
    description: "Paranormal investigators help family.",
    genre: ["Horror","Thriller"],
    mood: ["Dark","Suspenseful"],
    contentType: "Movie",
    ageRating: "18+",
    country: "USA",
    releaseYear: 2013,
    rating: 7.5,
    poster: "https://image.tmdb.org/t/p/w500/wVYREutTvI2tmxr6ujrHT704wGF.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/nYfVtq3LzJPSmF2fNzsl0AqM2QW.jpg",
    trailer: "https://www.youtube.com/embed/k10ETZ41q5o",
    duration: "1h 52m",
    pace: "Fast",
    tags: ["horror","ghost"],
    director: "James Wan",
    originalLanguage: "English",
    popularity: 8300,
    isTrending: false,
    isTopRated: false
  },
  {
    title: "The Notebook",
    description: "A romantic love story.",
    genre: ["Romance","Drama"],
    mood: ["Emotional"],
    contentType: "Movie",
    ageRating: "13+",
    country: "USA",
    releaseYear: 2004,
    rating: 7.8,
    poster: "https://image.tmdb.org/t/p/w500/qom1SZSENdmHFNZBXbtJAU0WTlC.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/6jajFcaY2YbQsx4y4xqXW9nQq9C.jpg",
    trailer: "https://www.youtube.com/embed/FC6biTjEyZw",
    duration: "2h 3m",
    pace: "Slow",
    tags: ["romance","love"],
    director: "Nick Cassavetes",
    originalLanguage: "English",
    popularity: 7500,
    isTrending: false,
    isTopRated: true
  },
  {
    title: "Oppenheimer",
    description: "The story of J. Robert Oppenheimer.",
    genre: ["Drama"],
    mood: ["Intense","Thought-provoking"],
    contentType: "Movie",
    ageRating: "13+",
    country: "USA",
    releaseYear: 2023,
    rating: 8.4,
    poster: "https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/fm6KqXn30Sk0fM6DItxIuGgLwVf.jpg",
    trailer: "https://www.youtube.com/embed/uYPbbksJxIg",
    duration: "3h",
    pace: "Medium",
    tags: ["biography"],
    director: "Christopher Nolan",
    originalLanguage: "English",
    popularity: 9200,
    isTrending: true,
    isTopRated: true
  },
  {
    title: "Tenet",
    description: "Time inversion spy thriller.",
    genre: ["Sci-Fi","Action"],
    mood: ["Intense"],
    contentType: "Movie",
    ageRating: "13+",
    country: "USA",
    releaseYear: 2020,
    rating: 7.5,
    poster: "https://image.tmdb.org/t/p/w500/k68nPLbIST6NP96JmTxmZijEvCA.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/wzJRB4MKi3yK138bJyuL9nx47y6.jpg",
    trailer: "https://www.youtube.com/embed/LdOM0x0XDMo",
    duration: "2h 30m",
    pace: "Fast",
    tags: ["time"],
    director: "Christopher Nolan",
    originalLanguage: "English",
    popularity: 8200,
    isTrending: false,
    isTopRated: true
  },
  {
    title: "Ford v Ferrari",
    description: "Racing rivalry.",
    genre: ["Drama","Action"],
    mood: ["Fast-paced"],
    contentType: "Movie",
    ageRating: "13+",
    country: "USA",
    releaseYear: 2019,
    rating: 8.1,
    poster: "https://image.tmdb.org/t/p/w500/tLFIMuPWVDqThK6zGk0oX1DIfj4.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/xJWPZIYOEFIpZfA7EQf00NfAofD.jpg",
    trailer: "https://www.youtube.com/embed/zyYgDtY2AMY",
    duration: "2h 32m",
    pace: "Fast",
    tags: ["cars"],
    director: "James Mangold",
    originalLanguage: "English",
    popularity: 8300,
    isTrending: false,
    isTopRated: true
  },
  {
    title: "The Grand Budapest Hotel",
    description: "Adventures of concierge.",
    genre: ["Comedy","Drama"],
    mood: ["Lighthearted"],
    contentType: "Movie",
    ageRating: "13+",
    country: "USA",
    releaseYear: 2014,
    rating: 8.1,
    poster: "https://image.tmdb.org/t/p/w500/eWdyYQreja6JGCzqHWXpWHDrrPo.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/1Ewt2zBtcxN2Wk6FIfK23p0g1g8.jpg",
    trailer: "https://www.youtube.com/embed/1Fg5iWmQjwk",
    duration: "1h 40m",
    pace: "Medium",
    tags: ["comedy"],
    director: "Wes Anderson",
    originalLanguage: "English",
    popularity: 7800,
    isTrending: false,
    isTopRated: true
  },
  {
    title: "1917",
    description: "WW1 mission.",
    genre: ["Drama"],
    mood: ["Intense"],
    contentType: "Movie",
    ageRating: "15+",
    country: "USA",
    releaseYear: 2019,
    rating: 8.2,
    poster: "https://image.tmdb.org/t/p/w500/iZf0KyrE25z1gagesZ1mO528XjG.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/21Q8bRxRt0ZncezRilIblK5zY0n.jpg",
    trailer: "https://www.youtube.com/embed/gZjQROMAh_s",
    duration: "1h 59m",
    pace: "Fast",
    tags: ["war"],
    director: "Sam Mendes",
    originalLanguage: "English",
    popularity: 8400,
    isTrending: false,
    isTopRated: true
  },
  {
    title: "Prisoners",
    description: "Kidnapping mystery.",
    genre: ["Thriller","Drama"],
    mood: ["Dark"],
    contentType: "Movie",
    ageRating: "18+",
    country: "USA",
    releaseYear: 2013,
    rating: 8.1,
    poster: "https://image.tmdb.org/t/p/w500/prsz1Q2Ew8S6IuHn1h0s43ZED6n.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/n2j0Yk51yXzTuhS5mR5yYjPq5nZ.jpg",
    trailer: "https://www.youtube.com/embed/bpXfcTF6iVk",
    duration: "2h 33m",
    pace: "Medium",
    tags: ["crime"],
    director: "Denis Villeneuve",
    originalLanguage: "English",
    popularity: 8300,
    isTrending: false,
    isTopRated: true
  },
  {
    title: "Gone Girl",
    description: "Missing wife mystery.",
    genre: ["Thriller"],
    mood: ["Dark"],
    contentType: "Movie",
    ageRating: "18+",
    country: "USA",
    releaseYear: 2014,
    rating: 8.1,
    poster: "https://image.tmdb.org/t/p/w500/qymaEx4xOBrY1Z6nQ4W4Q21zLbw.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/nZ31aF4B3c9w7aQ5kR2Q0vIq0mK.jpg",
    trailer: "https://www.youtube.com/embed/2-_-1nJf8Vg",
    duration: "2h 29m",
    pace: "Medium",
    tags: ["mystery"],
    director: "David Fincher",
    originalLanguage: "English",
    popularity: 8300,
    isTrending: false,
    isTopRated: true
  },
  {
    title: "The Irishman",
    description: "Mob hitman story.",
    genre: ["Drama"],
    mood: ["Slow-paced","Intense"],
    contentType: "Movie",
    ageRating: "18+",
    country: "USA",
    releaseYear: 2019,
    rating: 7.8,
    poster: "https://image.tmdb.org/t/p/w500/mbm8k3GFhXS0ROd9AD1gqYbIFbM.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/8jWk08u4j0M3U4tD0rA1QhP9m1y.jpg",
    trailer: "https://www.youtube.com/embed/WHXxVmeGQUc",
    duration: "3h 30m",
    pace: "Slow",
    tags: ["mafia"],
    director: "Martin Scorsese",
    originalLanguage: "English",
    popularity: 7900,
    isTrending: false,
    isTopRated: true
  },
  {
    title: "Blade Runner 2049",
    description: "Future dystopian world.",
    genre: ["Sci-Fi"],
    mood: ["Slow-paced"],
    contentType: "Movie",
    ageRating: "15+",
    country: "USA",
    releaseYear: 2017,
    rating: 8.0,
    poster: "https://image.tmdb.org/t/p/w500/gajva2L0rPYkEWjzgFlBXCAVBE5.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/ilRyazdflIgEqO5VDlsmQaTfqrm.jpg",
    trailer: "https://www.youtube.com/embed/gCcx85zbxz4",
    duration: "2h 44m",
    pace: "Slow",
    tags: ["future"],
    director: "Denis Villeneuve",
    originalLanguage: "English",
    popularity: 8000,
    isTrending: false,
    isTopRated: true
  },
  {
    title: "Avatar",
    description: "A marine on alien planet Pandora.",
    genre: ["Sci-Fi","Adventure"],
    mood: ["Emotional"],
    contentType: "Movie",
    ageRating: "13+",
    country: "USA",
    releaseYear: 2009,
    rating: 7.8,
    poster: "https://wallpapercat.com/w/full/1/2/6/127254-1536x2732-samsung-hd-avatar-background-photo.jpg",
    backdrop: "https://wallpapers.com/images/featured/avatar-background-8t5bkculh0jr4m3c.jpg",
    trailer: "https://www.youtube.com/embed/5PSNL1qE6VY",
    duration: "2h 42m",
    pace: "Medium",
    tags: ["aliens"],
    director: "James Cameron",
    originalLanguage: "English",
    popularity: 9100,
    isTrending: false,
    isTopRated: true
  },
  {
    title: "Avatar The Way of Water",
    description: "Return to Pandora.",
    genre: ["Sci-Fi","Adventure"],
    mood: ["Emotional"],
    contentType: "Movie",
    ageRating: "13+",
    country: "USA",
    releaseYear: 2022,
    rating: 7.7,
    poster: "https://wallpapercat.com/w/full/5/9/2/1590267-1080x1920-mobile-1080p-avatar-the-way-of-water-background-image.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/s16H6tpK2utvwDtzZ8Qy4qm5Emw.jpg",
    trailer: "https://www.youtube.com/embed/d9MyW72ELq0",
    duration: "3h 12m",
    pace: "Medium",
    tags: ["pandora"],
    director: "James Cameron",
    originalLanguage: "English",
    popularity: 9000,
    isTrending: true,
    isTopRated: true
  },
  {
    title: "Doctor Strange",
    description: "A surgeon becomes sorcerer.",
    genre: ["Action","Fantasy"],
    mood: ["Fast-paced"],
    contentType: "Movie",
    ageRating: "13+",
    country: "USA",
    releaseYear: 2016,
    rating: 7.5,
    poster: "https://image.tmdb.org/t/p/w500/uGBVj3bEbCoZbDjjl9wTxcygko1.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/sF1U4EUQS8YHUYjNrmvL0r4r000.jpg",
    trailer: "https://www.youtube.com/embed/HSzx-zryEgM",
    duration: "1h 55m",
    pace: "Fast",
    tags: ["marvel"],
    director: "Scott Derrickson",
    originalLanguage: "English",
    popularity: 8700,
    isTrending: false,
    isTopRated: false
  },
  {
    title: "Spider Man No Way Home",
    description: "Multiverse spider-man.",
    genre: ["Action"],
    mood: ["Emotional"],
    contentType: "Movie",
    ageRating: "13+",
    country: "USA",
    releaseYear: 2021,
    rating: 8.3,
    poster: "https://i.pinimg.com/originals/c2/35/40/c23540c326d441b466efa8ada61ccf09.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/14QbnygCuTO0vl7CAFmPf1fgZfV.jpg",
    trailer: "https://www.youtube.com/embed/JfVOs4VSpmA",
    duration: "2h 28m",
    pace: "Fast",
    tags: ["marvel"],
    director: "Jon Watts",
    originalLanguage: "English",
    popularity: 9500,
    isTrending: true,
    isTopRated: true
  },
  {
    title: "The Silence of the Lambs",
    description: "FBI agent hunts serial killer.",
    genre: ["Thriller"],
    mood: ["Dark"],
    contentType: "Movie",
    ageRating: "18+",
    country: "USA",
    releaseYear: 1991,
    rating: 8.6,
    poster: "https://image.tmdb.org/t/p/w500/uS9m8OBk1A8eM9I042bx8XXpqAq.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/5KXpwT5GtdqW0ZzSjE68J6yI943.jpg",
    trailer: "https://www.youtube.com/embed/W6Mm8Sbe__o",
    duration: "1h 58m",
    pace: "Medium",
    tags: ["crime"],
    director: "Jonathan Demme",
    originalLanguage: "English",
    popularity: 8200,
    isTrending: false,
    isTopRated: true
  },
  {
    title: "Se7en",
    description: "Detectives track serial killer.",
    genre: ["Thriller"],
    mood: ["Dark"],
    contentType: "Movie",
    ageRating: "18+",
    country: "USA",
    releaseYear: 1995,
    rating: 8.6,
    poster: "https://image.tmdb.org/t/p/w500/6yoghtyTpznpAsOUflxoXAzTaXp.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/2n001Bv2pT1qG97nQYQZCQo2135.jpg",
    trailer: "https://www.youtube.com/embed/znmZoVkCjpI",
    duration: "2h 7m",
    pace: "Medium",
    tags: ["crime"],
    director: "David Fincher",
    originalLanguage: "English",
    popularity: 8300,
    isTrending: false,
    isTopRated: true
  },
  {
    title: "The Departed",
    description: "Undercover cops and mob.",
    genre: ["Thriller","Drama"],
    mood: ["Intense"],
    contentType: "Movie",
    ageRating: "18+",
    country: "USA",
    releaseYear: 2006,
    rating: 8.5,
    poster: "https://image.tmdb.org/t/p/w500/11aA4B1M1G7Q0IAn2vSksF44D0L.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/qQoJgLq5h5eL22ItrP240k7v2R.jpg",
    trailer: "https://www.youtube.com/embed/iojhqm0JTW4",
    duration: "2h 31m",
    pace: "Fast",
    tags: ["mafia"],
    director: "Martin Scorsese",
    originalLanguage: "English",
    popularity: 8400,
    isTrending: false,
    isTopRated: true
  },
  {
    title: "The Green Mile",
    description: "Prison guards meet mysterious inmate.",
    genre: ["Drama"],
    mood: ["Emotional"],
    contentType: "Movie",
    ageRating: "15+",
    country: "USA",
    releaseYear: 1999,
    rating: 8.6,
    poster: "https://image.tmdb.org/t/p/w500/8VG8fDNiy50H4FedGwdSVUPxVKJ.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/lZpWprJqbIFpEV566IGcgVZ0000.jpg",
    trailer: "https://www.youtube.com/embed/Ki4haFrqSrw",
    duration: "3h 9m",
    pace: "Slow",
    tags: ["prison"],
    director: "Frank Darabont",
    originalLanguage: "English",
    popularity: 8500,
    isTrending: false,
    isTopRated: true
  },
  {
    title: "Inglourious Basterds",
    description: "WW2 revenge story.",
    genre: ["Action","Drama"],
    mood: ["Intense"],
    contentType: "Movie",
    ageRating: "18+",
    country: "USA",
    releaseYear: 2009,
    rating: 8.3,
    poster: "https://image.tmdb.org/t/p/w500/7sfbEnaARXDDhKm0CZ7D7uc2sbo.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/11BngBf8803Q040ZpZ3FwF4yI8R.jpg",
    trailer: "https://www.youtube.com/embed/KnrRy6kSFF0",
    duration: "2h 33m",
    pace: "Fast",
    tags: ["war"],
    director: "Quentin Tarantino",
    originalLanguage: "English",
    popularity: 8500,
    isTrending: false,
    isTopRated: true
  },
  {
    title: "Mad Max Fury Road",
    description: "Post apocalyptic chase.",
    genre: ["Action"],
    mood: ["Fast-paced"],
    contentType: "Movie",
    ageRating: "18+",
    country: "USA",
    releaseYear: 2015,
    rating: 8.1,
    poster: "https://image.tmdb.org/t/p/w500/hA2ple9q4cbjvNDZ1eZkE9lC0bM.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/nlCHUWjY9XWbuEUQauCBgnY8ymF.jpg",
    trailer: "https://www.youtube.com/embed/hEJnMQG9ev8",
    duration: "2h",
    pace: "Fast",
    tags: ["post apocalyptic"],
    director: "George Miller",
    originalLanguage: "English",
    popularity: 8400,
    isTrending: false,
    isTopRated: true
  },
  {
    title: "The Lion King",
    description: "Young lion becomes king.",
    genre: ["Animation"],
    mood: ["Emotional"],
    contentType: "Movie",
    ageRating: "All Ages",
    country: "USA",
    releaseYear: 1994,
    rating: 8.5,
    poster: "https://image.tmdb.org/t/p/w500/sKCr78AS8wq1gI0rE2B5eO9R0eX.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/5aXcB0h12ZbbM6d64H2mC62dE10.jpg",
    trailer: "https://www.youtube.com/embed/lFzVJEksoDY",
    duration: "1h 28m",
    pace: "Medium",
    tags: ["disney"],
    director: "Roger Allers",
    originalLanguage: "English",
    popularity: 8300,
    isTrending: false,
    isTopRated: true
  },
  {
    title: "Coco",
    description: "Boy enters land of dead.",
    genre: ["Animation"],
    mood: ["Feel-good","Emotional"],
    contentType: "Movie",
    ageRating: "All Ages",
    country: "USA",
    releaseYear: 2017,
    rating: 8.4,
    poster: "https://image.tmdb.org/t/p/w500/gGEsBPAijhVMCX3Q3Xh8IqUivhB.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/askg3SMvhqEl4OL52YpPfz10Z00.jpg",
    trailer: "https://www.youtube.com/embed/xlnPHQ3TLX8",
    duration: "1h 45m",
    pace: "Medium",
    tags: ["pixar"],
    director: "Lee Unkrich",
    originalLanguage: "English",
    popularity: 8400,
    isTrending: false,
    isTopRated: true
  },
  {
    title: "Toy Story",
    description: "Toys come alive.",
    genre: ["Animation"],
    mood: ["Lighthearted"],
    contentType: "Movie",
    ageRating: "All Ages",
    country: "USA",
    releaseYear: 1995,
    rating: 8.3,
    poster: "https://image.tmdb.org/t/p/w500/uXDfjJbdP4ijW5hWSBrPrlKpxab.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/3Rfvhy1Nl6sSGJwqA2gYq0E8q0L.jpg",
    trailer: "https://www.youtube.com/embed/v-PjgYDrg70",
    duration: "1h 21m",
    pace: "Medium",
    tags: ["pixar"],
    director: "John Lasseter",
    originalLanguage: "English",
    popularity: 8100,
    isTrending: false,
    isTopRated: true
  },
  {
    title: "Avengers Infinity War",
    description: "Heroes fight Thanos.",
    genre: ["Action"],
    mood: ["Intense"],
    contentType: "Movie",
    ageRating: "13+",
    country: "USA",
    releaseYear: 2018,
    rating: 8.4,
    poster: "https://image.tmdb.org/t/p/w500/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/mDfJG3LCkIqb67KIKU66X4Sm4R0.jpg",
    trailer: "https://www.youtube.com/embed/6ZfuNTqbHE8",
    duration: "2h 29m",
    pace: "Fast",
    tags: ["marvel"],
    director: "Russo Brothers",
    originalLanguage: "English",
    popularity: 9200,
    isTrending: false,
    isTopRated: true
  },
  {
    title: "Everything Everywhere All at Once",
    description: "A woman explores multiverse.",
    genre: ["Sci-Fi","Comedy","Action"],
    mood: ["Fast-paced","Emotional"],
    contentType: "Movie",
    ageRating: "15+",
    country: "USA",
    releaseYear: 2022,
    rating: 8.1,
    poster: "https://m.gettywallpapers.com/wp-content/uploads/2022/07/Everything-Everywhere-all-at-once-Background.jpg",
    backdrop: "https://images.wallpapersden.com/image/wxl-official-everything-everywhere-all-at-once-hd_82896.jpg",
    trailer: "https://www.youtube.com/embed/wxN1T1uxQ2g",
    duration: "2h 19m",
    pace: "Fast",
    tags: ["multiverse"],
    director: "Daniels",
    originalLanguage: "English",
    popularity: 8900,
    isTrending: true,
    isTopRated: true
  },
  {
    title: "Top Gun Maverick",
    description: "Pilot trains new recruits.",
    genre: ["Action"],
    mood: ["Fast-paced"],
    contentType: "Movie",
    ageRating: "13+",
    country: "USA",
    releaseYear: 2022,
    rating: 8.3,
    poster: "https://wallpapercat.com/w/full/1/b/a/369793-1080x2280-mobile-hd-top-gun-background-image.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/AaV1YIdWKnjAIAOe8UUKBFm327v.jpg",
    trailer: "https://www.youtube.com/embed/giXco2jaZ_4",
    duration: "2h 10m",
    pace: "Fast",
    tags: ["aviation"],
    director: "Joseph Kosinski",
    originalLanguage: "English",
    popularity: 9000,
    isTrending: true,
    isTopRated: true
  },
  {
    title: "The Batman Begins",
    description: "Batman origin story.",
    genre: ["Action"],
    mood: ["Dark"],
    contentType: "Movie",
    ageRating: "13+",
    country: "USA",
    releaseYear: 2005,
    rating: 8.2,
    poster: "https://image.tmdb.org/t/p/w500/8RW2runSEc34ZGZ9O1b5X7L4qF1.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/2va32apQP97gvUeaGLAQZCGREwX.jpg",
    trailer: "https://www.youtube.com/embed/neY2xVmOfUM",
    duration: "2h 20m",
    pace: "Medium",
    tags: ["batman"],
    director: "Christopher Nolan",
    originalLanguage: "English",
    popularity: 8500,
    isTrending: false,
    isTopRated: true
  },
  {
    title: "Lord of the Rings Fellowship",
    description: "Journey to destroy ring.",
    genre: ["Fantasy","Adventure"],
    mood: [],
    contentType: "Movie",
    ageRating: "13+",
    country: "USA",
    releaseYear: 2001,
    rating: 8.8,
    poster: "https://image.tmdb.org/t/p/w500/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/vI3aUGPuc4ebP3a7Iu2B8s1K59M.jpg",
    trailer: "https://www.youtube.com/embed/V75dMMIW2B4",
    duration: "2h 58m",
    pace: "Medium",
    tags: ["fantasy"],
    director: "Peter Jackson",
    originalLanguage: "English",
    popularity: 9200,
    isTrending: false,
    isTopRated: true
  },
  {
    title: "Lord of the Rings Return of the King",
    description: "Final battle.",
    genre: ["Fantasy"],
    mood: [],
    contentType: "Movie",
    ageRating: "13+",
    country: "USA",
    releaseYear: 2003,
    rating: 8.9,
    poster: "https://image.tmdb.org/t/p/w500/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/lXhgNSYcqGZKOa7uG0jAUK5uXTo.jpg",
    trailer: "https://www.youtube.com/embed/r5X-hFf6Bwo",
    duration: "3h 21m",
    pace: "Medium",
    tags: ["fantasy"],
    director: "Peter Jackson",
    originalLanguage: "English",
    popularity: 9300,
    isTrending: false,
    isTopRated: true
  },
  {
    title: "The Hobbit",
    description: "Adventure to reclaim kingdom.",
    genre: ["Fantasy"],
    mood: [],
    contentType: "Movie",
    ageRating: "13+",
    country: "USA",
    releaseYear: 2012,
    rating: 7.8,
    poster: "https://image.tmdb.org/t/p/w500/nJUHX3XL1jMkk8honUZnUmudFb9.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/jXv1H16VwU31i37yG25K1pXkL3Z.jpg",
    trailer: "https://www.youtube.com/embed/JTSoD4BBCJc",
    duration: "2h 49m",
    pace: "Medium",
    tags: ["fantasy"],
    director: "Peter Jackson",
    originalLanguage: "English",
    popularity: 8800,
    isTrending: false,
    isTopRated: true
  }
];

const seedData = async () => {
  try {
    await connectDB();
    
    // Clear existing movies
    await Movie.deleteMany({});
    console.log('🗑️  Cleared existing movies');
    
    // Drop problematic index if exists
    try {
      await Movie.collection.dropIndex({ genre: 1, mood: 1, country: 1, releaseYear: 1 });
      console.log('🗑️  Dropped old compound index');
    } catch (error) {
      console.log('ℹ️  Compound index not found or already dropped');
    }
    try {
      await Movie.collection.dropIndex({ title: 'text', description: 'text', tags: 'text' });
      console.log('🗑️  Dropped text index');
    } catch (error) {
      console.log('ℹ️  Text index not found or already dropped');
    }
    
    // Insert new movies one by one to identify issues
    for (let i = 0; i < movies.length; i++) {
      try {
        await Movie.create(movies[i]);
        console.log(`✅ Inserted movie ${i + 1}: ${movies[i].title}`);
      } catch (error) {
        console.error(`❌ Failed to insert movie ${i + 1}: ${movies[i].title} - ${error.message}`);
        break; // Stop on first error
      }
    }
    console.log(`✅ Successfully seeded movies`);
    
    process.exit(0);
  } catch (error) {
    console.error('❌ Error seeding data:', error);
    process.exit(1);
  }
};

seedData();